sudo: false
language: java

jdk:
  - oraclejdk8
  
script: mvn clean verify -P openwebbeans,simple-logging

after_success:
 - mvn clean test jacoco:report coveralls:report -P openwebbean,simple-slf4j -DrepoToken=XkBUcBKdzhG7VnpUuBlyfudlo3S61UKRB
