sudo: false
language: java

jdk:
  - oraclejdk8
  
script:
  - mvn clean verify jacoco:report -P openwebbeans,simple-logging

after_success:
 - mvn coveralls:report -P openwebbeans,simple-simple-logging -DrepoToken=XkBUcBKdzhG7VnpUuBlyfudlo3S61UKRB
